### ISSUE TITLE
any of implementation for a single hyper parameter

### ISSUE THREAD

**Issue by tmeshorer** [automl/ConfigSpace#161] opened 2020-09-17 02:32 UTC
Hi All,

Is there a way to implement "any of" sampling for a single hyperparameter? For example, in a decision tree the 
"max_features" hp, can have: int, float or {“auto”, “sqrt”, “log2”}, default=None

Hence, is there a way to define space for each possible option, and sample only from one of the spaces?

Thanks.

**Comment by mfeurer** [comment] 2021-12-14 14:34
Unfortunately, we do not support this at the moment.

Closing this as a duplicate of #113.

**Closed by mfeurer** 2021-12-14 14:34 UTC
