### ISSUE TITLE
Adding and removing choices for Categorical Hyperparameters

### ISSUE THREAD

**Issue by startakovsky** [automl/ConfigSpace#174] opened 2021-02-04 19:07 UTC
There is a use case to add/remove a choices for Categorical Hyperparameter, and when that happens obviously there may obviously be some automatic impact to conditions in the case of deleting choices.

Is there interest in the community about building such a feature? Is this in your "roadmap"?

Thanks

**Comment by mfeurer** [comment] 2021-02-17 20:04
> Is this in your "roadmap"?

I'm afraid we don't have a roadmap for new features but rather only maintain the library at this point due to time constraints.

There apparently was interest in adding new choices in the past via #70 and I can see how one would like that feature. Could you please give a (few) use case(s) for removing choices?

The adding part might be rather easy, but the deletion part may not be that easy. One would have to define what happens to conditions/forbiddens in case the removed value is mentioned.

If you're interested I'd suggest that you start with the addition to get familiar with the code and then fetch out the expected behavior of deletion.

**Comment by eddiebergman** [comment] 2024-07-12 14:08
I think the more general solution to this is further elevated to #296, as this asks how to update/delete a hyperparameter from a space.

From that discussion, I think the relevant decision made is that we don't support mutating existing hyperparameters, i.e. there is no way to modify a hyperparameter in place. This is mostly due to caching but also as it raises further questions of how to deal with conditional or forbiddens reliant on the existance of said values.

In principle, the easiest way to support this would be that we can add operations such as `with_removed(...names) -> ConfigurationSpace` which would return a new ConfigurationSpace with the change made. I will close this in favour of the more general topic at #296

**Closed by eddiebergman** 2024-07-12 14:08 UTC
