### ISSUE TITLE
Enforcing relations among hyperparameters

### ISSUE THREAD

**Issue by mhlr** [automl/ConfigSpace#248] opened 2022-04-25 02:25 UTC
Is there a way to specify that the value of one hyperparameter must be less than another. for example to specify an interval? I would imagine it would be implemented by a forbidden clause, but it does not seme possible using the forbidden clauses listed in the docs. Is there another way?
Currently I encode ordering violations in the oblective:

```
def objective(config):
  if confg['low'] ? config['high']:
     return big_number
  ... happy path ...
```

It would be cleaner to put this constratint in the configurartion though.
Also in the above workaround the violation still consumes a run,
whwreas with a config space constraint I would imagine the violation would just be rejected and not count towards the total number of runs.

**Comment by mfeurer** [comment] 2022-05-02 13:00
There's PR #245 which is on my reviewing list.

**Comment by mfeurer** [comment] 2022-05-02 13:18
Closing this as it is a duplicate of #198.

**Closed by mfeurer** 2022-05-02 13:18 UTC
